### ISSUE TITLE
requesting install instructions

### ISSUE THREAD

**Issue by cbrandlehner** [keerts/pyninjasphere#3]
How do I actually install this script?

**Comment by keerts** [comment]
That's a good one, it's so long ago that I used it. You still have a sphere running? I gave up ;-)

**Comment by keerts** [comment]
One way to use the script in isolation is to use virtualenv:

```
>  virtualenv /tmp/x
> source /tmp/x/bin/activate
```

Now go to the root of the pyninjasphere project and

```
> pip install .
> which pyninjasphere
/tmp/x/bin/pyninjasphere

```
```
> pyninjasphere
Usage: pyninjasphere [OPTIONS] COMMAND [ARGS]...
...
```

**Comment by keerts** [comment]
Let me know if that helps!

**Comment by keerts** [comment]
More info on python modules here http://docs.python-guide.org/en/latest/dev/virtualenvs/

**Comment by cbrandlehner** [comment]
Thank you. I was not spending lots of energy on NinjaSphere the last years but restarted using it to play around with some zigbee devices.
